### ISSUE TITLE
Use Case - OSPO scores updates

### ISSUE THREAD

**Issue by FelipeGuzmanSierra** [kommitters/bns#47]
## Context
An essential process related to open-source project management is the scorecard score. This score gives information about the security level of the project and the correctness of the code. The scorecard scores can be used as an indicator or as a KPI for a company's OKR. 

We need to add a use case to get the scorecard score of a group of projects from GitHub and update their values in a database on notion. 

This use case will imply the creation of a new component or term in the project structure. This new component should abstract the logic to write or update information on a destiny (like notion using an API). 

For this issue, we need to:
- [ ] Add a fetcher, mapper, and formatter for the scorecard score.
- [ ] Add a base class to abstract the update process on destiny. Then, a use case implementation for notion should be defined to cover the use case.

**Comment by L-Zuluaga** [comment]
Tackled on https://github.com/kommitters/bas/issues/87
